#
#   AUTO GENERATED by VDAPSEISUTILS
#   - Name    : {name}
#   - Source  : {source}
#   - Date    : {datetime}
#
#                     Configuration File for Fir
#
MyModId          MOD_FIR
InRing           WAVE_RING       # Transport ring to find waveform data on,
#OutRing         DEC_RING        # Transport ring to write output to,  UW SYSTEM
OutRing          FILTERPICK_RING # AQMS SYSTEM
                                 # InRing and OutRing may be the same.
HeartBeatInterval     30         # Heartbeat interval, in seconds,
LogFile                2         # 1 -> Keep log, 0 -> no log file
                                 # 2 -> write to module log but not to stderr or
                                 #   stdout
#Debug                           # Write out debug messages (optional)

MaxGap              2.5         # Maximum gap, in sample periods, allowed
                                # between trace data points.
                                # When exceeded, channel is restarted.

# Specify the filter frequency response characteristics with two or more
# commands fo the form: Band <f_low> <f_high> <level> <deviation>
#
# where:
#   f_low = low frequency limit of a band
#   f_high = high frequency limit of a band
#   level = desired level of the band: 1 for pass band, 0 for stop band
#   deviation = amount of ripple allowed from desired level
#
# All frequencies must be scaled to the range 0.0 - 1.0, where 1.0
# corresponds to the Nyquist frequency. (Nyquist frequency is half the sample
# rate and is the maximum frequency content that can be in a time series.)
# Note that the sampling rate is not known at configuration time, but will be
# gotten from the trace data packets as they're received at run-time.
# One band must start at 0.0 frequency; one band must end at 1.0 frequency. Any
# number of additional bands may be specified (up to a total of ten bands.)

# for 50 sps BH channel to cut things lower than 0.5 Hz
# changed from deviation of 0.005 to 0.07.  3/3/17 SDM
Band 0.0 0.02 0 0.07
Band 0.04 1.0 1 0.07

# an attempt at a weak notch filter at 0.16 Hz  DOESN'T WORK
#Band 0.000 0.004 1 0.1
#Band 0.005 0.008 0 0.1
#Band 0.010 1.000 1 0.1

# If you want Fir to compute and log its filter coefficients and then
# exit, specify "TestMode".
#TestMode

#
# Specify logos of the messages to grab from the InRing.
# TYPE_TRACEBUF is assumed, therefore only module ID and
# installation ID need to be specified
#
GetWavesFrom    INST_WILDCARD MOD_WILDCARD  # TYPE_TRACEBUF (assumed)

#
# List SCNL codes of trace messages to fir and their output SCNL codes
# Wildcard characters are not allowed here.
#
#        IN-SCNL     OUT-SCNL
{station_lines}
